version: '2'
services:
  fluentd:
    build:
      context: .
      dockerfile: FluentdDockerfile
    ports:
     - 24224:24224 
     - 5140:5140
     - 5140:5140/udp
    volumes:
     - /docker/fluentd:/fluentd/log
     - .:/fluentd/etc
    environment:
     - FLUENTD_CONF=fluentd.conf
    links:
     - elasticsearch
    restart: always

  elasticsearch:
    image: elasticsearch:5.1-alpine
    ports:
     - 9200:9200
    volumes:
     - ./data/elastic:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: kibana:5.1
    ports:
     - 5601:5601
    links:
     - elasticsearch
    restart: always
